site_name: Lighter
theme:
  icon:
    repo: fontawesome/brands/github
  font:
    code: Roboto Mono
  name: material
  favicon: assets/images/lighter_favicon.png
  logo: assets/images/lighter_logo.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - content.tooltips
    - footnotes
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/circle-half-stroke
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: fontawesome/solid/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to system preference

extra_css:
  - assets/extra.css

# Plugins
# Auto API reference generation: https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages
plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          docstring_style: google
          options:
            # Removed the default filter that excludes private members (that is, members whose names start with a single underscore).
            filters: null

nav:
  - Home: index.md
  - Tutorials:
      - Configuration Basics: tutorials/01_configuration_basics.md
      - Image Classification: tutorials/02_image_classification.md
      - Semantic Segmentation: tutorials/03_semantic_segmentation.md
      - Transfer Learning: tutorials/04_transfer_learning.md
      - Multi-task Learning: tutorials/05_multi_task_learning.md
  - How-To:
      - Custom Project Modules: how-to/01_custom_project_modules.md
      - Debugging Config Errors: how-to/02_debugging_config_errors.md
      - Creating a Custom Metric: how-to/03_creating_a_custom_metric.md
      - Using Adapters: how-to/04_using_adapters.md
      - Using and Extending Writers: how-to/05_using_and_extending_writers.md
      - Using Freezer: how-to/06_using_freezer.md
      - Implementing a Custom Inferer: how-to/07_implementing_a_custom_inferer.md
  - Explanation:
      - Overview: explanation/01_overview.md
      - Configuration System: explanation/02_configuration_system.md
      - Adapter System: explanation/03_adapter_system.md
      - Dynamic Module Loading: explanation/04_dynamic_module_loading.md
  - API Reference: reference/
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html      
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - admonition
  - pymdownx.details
  - pymdownx.superfences      
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_name: project-lighter/lighter
repo_url: https://github.com/project-lighter/lighter
